### ISSUE TITLE
[multiple instances] Modal Warning "Only one instance..." message is annoying

### ISSUE THREAD

**Issue by vodihu** [zarunbal/LogExpert#245]
I like to have only one instance of Logexpert, as settings "view Settings => Allow only 1 Instance" assume. But I could not get rid of this annoying Messagebox.

- LogExpert Version: 1.9.0
- Windows Version: 11

![image](https://user-images.githubusercontent.com/66322119/179974263-5b895bb9-90ba-4043-ae1c-88d9b7e6699d.png)

Thanke you very much, for keeping Logexpert alive!

**Comment by Hirogen** [comment]
Ah I see, problem is, you get the error message always, even after the first time, that is quite annoying

**Comment by hugosius** [comment]
Also for me, this message is not useful in any way. A "Don't show again" option as suggested by @GeneralMidiRotkiv would do just fine.
Besides, LogExpert is a great an very helpful tool. Thanks for that!

**Comment by Hirogen** [comment]
It is fixed, but currently the Settings-Dialog does not import the Settings when it is opened, only when Logexpert is started, this needs to be taken into account, so the "option" to "not show the error message" has a wrong state in the settings dialog.

**Comment by pferrucci** [comment]
+1
This is new in 1.9.0
With previous version, running "Logexpert myfile" would open it in a new tab. That was nice.
Waiting for a new binary release if it was fixed.

Thanks

**Comment by hugosius** [comment]
We would also appreciate a new release since the issue seems to be fixed...

**Comment by RandallFlagg** [comment]
@zarunbal is this issue solved in the .net 8 version? If yes, can it be closed?

**Comment by vodihu** [comment]
> [@Hirogen](https://github.com/Hirogen) is this issue solved in the .net 8 version? If yes, can it be closed?

Sorry, but I could not proof this. The first call from cmd-shell works fine, but every further call gives me a 

![Image](https://github.com/user-attachments/assets/71aaaca3-b73b-47d1-a8a6-ffd2718bace3)

But the first impression of the new interface is very promessing!

**Comment by Hirogen** [comment]
yeah the problem is, that the grpc is not completely implemented yet and currently works as a band-aid

**Comment by vodihu** [comment]
FYI: Still the same error in [Release 1.11.0 .net 8](https://github.com/zarunbal/LogExpert/releases/tag/v.1.11.0)

**Comment by RandallFlagg** [comment]
@Hirogen is this related to #283?

**Comment by Hirogen** [comment]
yeah the are all related, need to implement grpc asap 😅

**Comment by Hirogen** [comment]
Removed GRPC and added NamedPipes, port should no longer be a problem, with the next release this should be solved
